let weatherTypes = new Map();
weatherTypes.set('NA','Not available');
weatherTypes.set('0','Clear night');
weatherTypes.set('1','Sunny day');
weatherTypes.set('2','Partly cloudy (night)');
weatherTypes.set('3','Partly cloudy (day)');
weatherTypes.set('4','Not used');
weatherTypes.set('5','Mist');
weatherTypes.set('6','Fog');
weatherTypes.set('7','Cloudy');
weatherTypes.set('8','Overcast');
weatherTypes.set('9','Light rain shower (night)');
weatherTypes.set('10','Light rain shower (day)');
weatherTypes.set('11','Drizzle');
weatherTypes.set('12','Light rain');
weatherTypes.set('13','Heavy rain shower (night)');
weatherTypes.set('14','Heavy rain shower (day)');
weatherTypes.set('15','Heavy rain');
weatherTypes.set('16','Sleet shower (night)');
weatherTypes.set('17','Sleet shower (day)');
weatherTypes.set('18','Sleet');
weatherTypes.set('19','Hail shower (night)');
weatherTypes.set('20','Hail shower (day)');
weatherTypes.set('21','Hail');
weatherTypes.set('22','Light snow shower (night)');
weatherTypes.set('23','Light snow shower (day)');
weatherTypes.set('24','Light snow');
weatherTypes.set('25','Heavy snow shower (night)');
weatherTypes.set('26','Heavy snow shower (day)');
weatherTypes.set('27','Heavy snow');
weatherTypes.set('28','Thunder shower (night)');
weatherTypes.set('29','Thunder shower (day)');
weatherTypes.set('30','Thunder');