let weatherTypes = new Map();
weatherTypes.set('NA',{'$':'Not available','f':'f02e'});
weatherTypes.set('0',{'$':'Clear night','f':'f00d'});
weatherTypes.set('1',{'$':'Sunny day','f':'f00d'});
weatherTypes.set('2',{'$':'Partly cloudy (night)','f':'f086'});
weatherTypes.set('3',{'$':'Partly cloudy (day)','f':'f002'});
weatherTypes.set('4',{'$':'Not used','f':'f002'});
weatherTypes.set('5',{'$':'Mist','f':'f0014'});
weatherTypes.set('6',{'$':'Fog','f':'f014'});
weatherTypes.set('7',{'$':'Cloudy','f':'f041'});
weatherTypes.set('8',{'$':'Overcast','f':'f00c'});
weatherTypes.set('9',{'$':'Light rain shower (night)','f':'f029'});
weatherTypes.set('10',{'$':'Light rain shower (day)','f':'f006'});
weatherTypes.set('11',{'$':'Drizzle','f':'f006'});
weatherTypes.set('12',{'$':'Light rain','f':'f006'});
weatherTypes.set('13',{'$':'Heavy rain shower (night)','f':'f028'});
weatherTypes.set('14',{'$':'Heavy rain shower (day)','f':'f008'});
weatherTypes.set('15',{'$':'Heavy rain','f':'f008'});
weatherTypes.set('16',{'$':'Sleet shower (night)','f':'f0b4'});
weatherTypes.set('17',{'$':'Sleet shower (day)','f':'f0b2'});
weatherTypes.set('18',{'$':'Sleet','f':'f0b2'});
weatherTypes.set('19',{'$':'Hail shower (night)','f':'f032'});
weatherTypes.set('20',{'$':'Hail shower (day)','f':'f004'});
weatherTypes.set('21',{'$':'Hail','f':'f004'});
weatherTypes.set('22',{'$':'Light snow shower (night)','f':'f028'});
weatherTypes.set('23',{'$':'Light snow shower (day)','f':'f006'});
weatherTypes.set('24',{'$':'Light snow','f':'f00a'});
weatherTypes.set('25',{'$':'Heavy snow shower (night)','f':'f02a'});
weatherTypes.set('26',{'$':'Heavy snow shower (day)','f':'f00a'});
weatherTypes.set('27',{'$':'Heavy snow','f':'f00a'});
weatherTypes.set('28',{'$':'Thunder shower (night)','f':'f020'});
weatherTypes.set('29',{'$':'Thunder shower (day)','f':'f010'});
weatherTypes.set('30',{'$':'Thunder','f':'f010'});